language: java
jdk: openjdk13
git:
  depth: false
addons:
  sonarcloud:
    organization: "saharatul"
    token:
      secure: "bHfjjQSZ43qT1DTR0vb3WOAPSeGO20SXXhTS/0QcWUyg8c3xqHLQ0nUXmNvuOc+Sw3aRHXI9dlYqFkGAQ3+tcayVZeKqVCAgLjadJXg74y1dP0A0cwcAxdo6NzI8gEWCWOoIBWJG5eYutsgRfTZsrkEAOyEmhceDtcp/bKXlOIgrTXC6flrhRrIIbI+BpSx/BR08OaY0F2j3b3I7bYsZ9mxvc1GT4z6lZDR+7cu5z+ftbhe6SvgzLWYs26MynAkYwk/ldHZptn4WvUtZyasuBhd1rSirBjZ5JvPprtX5tfWSP1gaEswWv2PKwlzBfw6A6eyicJfPWxTjhuQcsf80N5raPV0wayYCVvgHpYY1Pqf+s61Cxoq/iUKmgJtwaQJJGnEUqx0Z+HnBLgInXjYO/v3veCLiXfE8QvAFTSoI0tDDLJ/TZ2nEuFAO1LIXgWN84l4MV0aMODuH3Z0D0esASe+pGUx8/5c9d4qnKDcwAzR7iz2uObPf6eGlKo53F/XI43A+aURXF3lIYT/zCPMzSgt9DJhVOKNoupahURrUlC+j7OI4kXYBTkvJU5u8vcvkEfbNOL6uQ5ZQ1fXayylKtOk+SzCWLBgT5KrP9gcaVcs8C/r8oZ5RD/tUN0RU0B2dfmHS9NcZAVyh9yspkIftCW0crKeg8+87EyC7rrJHS0E="
script:
  - gradle sonarqube